dtype, ndim , shape,

In [8]:
import numpy as np
dtype_array = np.array(
   [ [1, 2, 3],
    [3, 2, 1],
    [2, 1, 3]]
)
print(dtype_array.ndim)
print(dtype_array.dtype)
print(dtype_array.shape)

2
int64
(3, 3)


Create an array with all zeros and ones


In [21]:
zero_array = np.zeros((3, 3))
print(zero_array)  
print(zero_array.shape)

one_array = np.ones((3, 3))
print(one_array)
print(one_array.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)


create a array with spacific value

In [22]:
sp_array = np.full(
    shape = (3, 3),
    fill_value = 5,
)
print(sp_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


create an identity matrix

In [23]:
iden_array = np.eye(3)
print(iden_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


create a sequential number 

In [25]:
seq_array = np.arange(
    start = 0,
    stop = 10,
    step = 1,
)
print(seq_array)

[0 1 2 3 4 5 6 7 8 9]


create a linspace array 

In [28]:
lin_array = np.linspace(
    start = 0,
    stop = 10,
    num = 5,
)   
print(lin_array)


[ 0.   2.5  5.   7.5 10. ]


slice in array

In [31]:
slice_array = np.array (
    [ [1, 2, 3],
     [3, 2, 1],
     [2, 1, 3]]
)
print(slice_array[0:2, 1:3]) # 2

[[2 3]
 [2 1]]


Reshape

In [32]:
reshape_array = np.array(
    [ [1, 2, 3, 5],
     [3, 2, 1, 7],
     [2, 1, 3, 9],
     [3, 5, 7, 8],
     [3, 4, 6, 8]]
)
print(reshape_array.reshape(4,5)) # 1x9

[[1 2 3 5 3]
 [2 1 7 2 1]
 [3 9 3 5 7]
 [8 3 4 6 8]]


Sort and reverse sort

In [ ]:
sort_array = np.array([6,8,7,5,0,4,3,2,1,5,0,7,0,5,4,0,1])
sort_array.sort()
print(sort_array) 

reverse_sort = sort_array
print(reverse_sort[::-1]) 

[0 0 0 0 1 1 2 3 4 4 5 5 5 6 7 7 8]
[1 0 0 0]
