dtype, ndim , shape,

In [148]:
import numpy as np
dtype_array = np.array(
   [ [1, 2, 3],
    [3, 2, 1],
    [2, 1, 3]
    ]
)
print(dtype_array.ndim)
print(dtype_array.dtype)
print(dtype_array.shape)

2
int64
(3, 3)


Create an array with all zeros and ones


In [149]:
zero_array = np.zeros((3, 3), dtype=int)
print(zero_array)  
print(zero_array.shape)


one_array = np.ones((3, 3))
print(one_array)
print(one_array.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)


create a array with spacific value

In [126]:
sp_array = np.full(
    shape = (3, 3),
    fill_value = 5,
)
print(sp_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


create an identity matrix

In [127]:
iden_array = np.eye(3)
print(iden_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


create a sequential number 

In [128]:
seq_array = np.arange(
    start = 0,
    stop = 10,
    step = 1,
)
print(seq_array)

[0 1 2 3 4 5 6 7 8 9]


create a linspace array 

In [129]:
lin_array = np.linspace(
    start = 0,
    stop = 10,
    num = 5,
)   
print(lin_array)


[ 0.   2.5  5.   7.5 10. ]


slice in array

In [130]:
slice_array = np.array (
    [ [1, 2, 3],
     [3, 2, 1],
     [2, 1, 3]]
)
print(slice_array[0:2, 1:3]) # 2

[[2 3]
 [2 1]]


Reshape

In [131]:
reshape_array = np.array(
    [ [1, 2, 3, 5],
     [3, 2, 1, 7],
     [2, 1, 3, 9],
     [3, 5, 7, 8],
     [3, 4, 6, 8]]
)
print(reshape_array.reshape(4,5)) # 1x9

[[1 2 3 5 3]
 [2 1 7 2 1]
 [3 9 3 5 7]
 [8 3 4 6 8]]


Sort and reverse sort

In [132]:
sort_array = np.array([6,8,7,5,0,4,3,2,1,5,0,7,0,5,4,0,1])
sort_array.sort()
print(sort_array) 

reverse_sort = sort_array
print(reverse_sort[::-1]) 

[0 0 0 0 1 1 2 3 4 4 5 5 5 6 7 7 8]
[8 7 7 6 5 5 5 4 4 3 2 1 1 0 0 0 0]


Argmax And Argmin

In [133]:
#Argmax 
argmax_array = np.array([[1, 8, 3],
                        [3, 2, 2],
                        [2, 3, 3]])
argmax_array= np.argmax(argmax_array)
print(argmax_array) # 2D => it's working in coloumn wise  



argmax_array1 = np.array([1, 318, 3, 343, 56, 78, 90, 112, 34, 56, 78, 93])
argmax_array1= np.argmax(argmax_array1)
print(argmax_array1) # 1D => it's working in array wise





#Argmin
argmin_array = np.array([[1, 8, 3],
                        [3, 2, 2],
                        [2, 3, 3]])
argmin_array= np.argmin(argmin_array)
print(argmin_array) # 2D => it's working in coloumn wise

argmin_array1 = np.array([21, 318, 3, 343, 56, 78, 90, 112, 34, 56, 78, 93])
argmin_array1= np.argmin(argmin_array1) 
print(argmin_array1) # 1D => it's working in array wise

1
3
0
2


Split

In [134]:
split_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_array = np.split(split_array, 3)
print(split_array) # 3 array of 3 elements each

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Dot Product

In [135]:
# dot_array = np.array([[1, 2 ],
#                      [3, 4 ]]
#                     )
# print(dot_array.dot(dot_array)) # 3x3 matrix multiplication

dor1 = np.array([1, 2])
dor2 = np.array([3, 4])
print(np.dot(dor1, dor2)) # 1x1 matrix multiplication

11


Matrix Transpose

In [136]:
array = np.array(
   [ [1, 2, 3 ],
    [5, 4, 3]])
print(array.transpose())

Matrix_Transpose = np.array( 
   [ [1, 2, 3],
      [4, 5, 6]])
print(Matrix_Transpose.transpose())
print("Transpose of the matrix is: ", Matrix_Transpose)



[[1 5]
 [2 4]
 [3 3]]
[[1 4]
 [2 5]
 [3 6]]
Transpose of the matrix is:  [[1 2 3]
 [4 5 6]]


mean, median,std

In [155]:
mean = np.mean([1, 2, 3, 4, 5],
               dtype=np.int32)
print( mean )

median = np.median([1, 3, 3, 4, 5],
                 )
print( median )#false

std = np.std([1, 2, 3, 4, 5],
               )  
print( std ) # 1.4142

3
3.0
1.4142135623730951


Numpy filtering

In [157]:
#Boolean method
# 1. Using boolean indexing to filter elements
my_array = np.array([1, 2, 3, 4, 5])
filer_mask = [True, False, True, False, True]
print(my_array[filer_mask]) # [1, 3, 5]

my_array = np.array([1, 2, 3, 4, 5])
filer_mask = my_array %2 == 0
print(my_array[filer_mask]) # [2, 4]

[1 3 5]
[2 4]


Vectorization

In [158]:
vector = np.array([1, 2, 3, 4, 5])
vectorzition = vector + 3
print(vectorzition) # [4, 5, 6, 7, 8]

[4 5 6 7 8]


Broadcasting

In [ ]:

a1 = np.array([2, 4, 6])

a2 = np.array([[1, 3, 5], 
               [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


Random

In [183]:
print(np.random.rand(3, 3)) # 3x3 random array


print(np.random.randint(100 ,size=(3, 3))) # 3x3 random array




randint = np.random.randint(50, size=(3, 3))
print(randint)# 3x3 random array



[[0.31367278 0.54404083 0.05293683]
 [0.90691696 0.60708648 0.02883439]
 [0.70642256 0.28514076 0.57004479]]
[[74 29  7]
 [79 52 80]
 [92 63 78]]
[[ 6 44 10]
 [40 47 33]
 [23 21 27]]
