Reshape

numpy Useful method 

In [18]:
import numpy as np
# Create a  array with 15 elements
reshape_array = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15,]])

print(reshape_array)
print(reshape_array.shape) 


# print(reshape_array.ndim)
# print(reshape_array.size)
# print(reshape_array.dtype)


# Reshape the array to 5 rows and 3 columns 2 dimension to 2 dimension
print(reshape_array.reshape(5,3))  
print(reshape_array.shape)




# Reshape the array to 3 rows and 5 columns 2 dimension to 3 dimension
print(reshape_array.reshape(1,3,5))     
print(reshape_array.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
(3, 5)


In [10]:
#reshaping with negetive value
one_array = np.ones(
    shape=(4,2,2,3)
)
print(one_array) # (4, 2, 2, 3)

# Reshape the 4D array to 3D array with 2 rows and 2 columns
reshape_array = one_array.reshape(2,2,-1) # -1 means it will be calculated automatically	
print(reshape_array) # (2, 2, 12)

print(reshape_array.shape) # (2, 2, 12)
print(reshape_array.ndim) # 3D array

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
(2, 2, 12)
3


In [11]:
funtion_random = np.empty(
    (5,3)) # 4 rows and 4 columns)
print(funtion_random)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]
 [6.4e-323 6.9e-323 7.4e-323]]


In [ ]:
# save_array = np.save('array.npy', funtion_random) # save the array to a file
# save_array = np.savez('array.npy', funtion_random)

# load_array = np.load('array.npy') # load the array from the file
# print(load_array) # print the loaded array
# # print the shape of the loaded array   


[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]
 [6.4e-323 6.9e-323 7.4e-323]]


In [13]:
len_array = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]])
print(len(len_array)) 
print(len_array.dtype) # <class 'list'>

3
int64


In [14]:
array = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

print(array.dtype) # <class 'numpy.ndarray'>

int64


In [15]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
reshape = array.reshape(5,3)
print(reshape) # (5, 3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [19]:
len_array = np.array(
    [1,2,3,4,5,6,7,8,9,10,
    11,12,13,14,15])
print(len(len_array)) 
print(len_array.dtype) # <class 'list'>

15
int64


Sort

In [34]:
#sorting the array
sort_array = np.array([4,2,8,9,1,3,5,7,6])
sort_array.sort() # sort the array in ascending order
print(sort_array) # [1 2 3 4 5 6 7 8 9]
reverse_sort = np.sort(sort_array)[::-1] # sort the array in descending order
print(reverse_sort) # [9 8 7 6 5 4 3 2 1]




[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [36]:
#reversing sort the array
reverse_array = np.array([4,2,8,9,1,3,5,7,6])
# reverse_array.sort()  # sort the array in descending order
# reverse_sort_array = reverse_array[::-1] # reverse the array
# print(reverse_sort_array) # [9 8 7 6 5 4 3 2 1]
reverse_array = np.sort(reverse_array)[::-1] # sort the array in descending order
print(reverse_array) # [9 8 7 6 5 4 3 2 1]

[9 8 7 6 5 4 3 2 1]
