Dot product

In [17]:
#Dot product
import numpy as np
dot_product = np.array([1, 2, 3])
dot_product1 = np.array([4, 5, 6])
                   
dot_product = np.dot(dot_product, dot_product1)
print("Dot product of two arrays is: ", dot_product)




Dot product of two arrays is:  32


Matrix Transpose


In [18]:
Matrix_Transpose = np.array( 
   [ [1, 2, 3],
      [4, 5, 6]])
print(Matrix_Transpose.transpose())
# print("Transpose of the matrix is: ", Matrix_Transpose)


[[1 4]
 [2 5]
 [3 6]]


Mean

In [ ]:
#Mean => average of the numbers
mean = np.array([3.5, 4.5, 5.5, 6.5])
mean = np.mean(mean)
print(mean)

5.0


Median

In [ ]:
#Median => middle value of the numbers but before that we need to sort the numbers
#median is a notgood
median = np.array([3.5, 4.5, 5.5, 6.5])
median = np.median(median)
print(median)

5.0


Standerd devition

In [ ]:
#standard deviation => measure of the amount of variation or dispersion of a set of values
#standard deviation is a good measure of the spread of the data 
standard_deviation = np.array([3.5, 4.5, 5.5, 6.5])
print( np.std(standard_deviation))


1.118033988749895


Vectorization

In [ ]:
#vactorization => is a process of converting a function into a vector form. vactiorization must better performance than the for loop. loop is slow and vactorization is fast.

veactor = np.array([1, 2, 3])
veactor1 = veactor + 5
print(veactor1)

[6 7 8]


Broadcasting

In [ ]:
# broadcasting => is a process of converting one data type into another data type. for example, if we have an array of integers and we want to convert 
# it into an array of floats, we can use broadcasting.
# Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
# It automatically expands the smaller array across the larger array so that they have compatible shapes.
# Broadcasting is useful for vectorized operations and can lead to more efficient code.
# It is important to note that broadcasting only works when the dimensions of the arrays are compatible.
# If the dimensions are not compatible, NumPy will raise a ValueError.


broadcasting = np.array([1, 2, 3])
broadcasting1 = np.array([4, 5, 6])
print(broadcasting * broadcasting1)


[ 4 10 18]
