Reshape

In [ ]:
import numpy as np
# Create a  array with 15 elements
reshape_array = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15,]])

print(reshape_array)
print(reshape_array.shape) 


# print(reshape_array.ndim)
# print(reshape_array.size)
# print(reshape_array.dtype)


# Reshape the array to 5 rows and 3 columns 2 dimension to 2 dimension
print(reshape_array.reshape(5,3))  
print(reshape_array.shape)




# Reshape the array to 3 rows and 5 columns 2 dimension to 3 dimension
print(reshape_array.reshape(1,3,5))     






[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
