Axis

In [7]:
# # first dimensional -> axis = 0
# # second dimensional -> axis = 1
# # third dimensional -> axis = 2
# Nth dimensional -> axis = N-1


import numpy as np

axis_array = np.array( 
    [[1, 2, 3], 
     [4, 5, 6],
       [7, 8, 9]])
print(axis_array)
print(axis_array.ndim)  # (3, 3) -> 2D array with 3 rows and 3 columns
print (np.sum(axis_array, axis=0))  # sum of each column
print (np.sum(axis_array, axis=1))  # sum of each row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[12 15 18]
[ 6 15 24]
