array slicing 

In [1]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,9,9],
    [5,6,8,10]]
)
print (slc_array[2:4,1:3 ])

[[5 9]
 [6 8]]


In [3]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,7,9],
    [5,6,8,10]]
)
print (slc_array[1:4,2:3 ])


[[6]
 [7]
 [8]]


In [ ]:

zero_array = np.zeros((3,4))
print (zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
