In [1]:
import numpy as np
zero_array = np.zeros((3, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
iter_array = [1, 2, 3, 4, 5, 6]
for i in iter_array:
    print(i)

1
2
3
4
5
6


In [5]:
iter_array2 = [9, 8, 7, 6, 5, 4]
for i in range ( len(iter_array2)):
    print(iter_array2[i])   

9
8
7
6
5
4


In [7]:
seq_array = np.arange(1, 10, 2)
print(seq_array)

[1 3 5 7 9]


In [8]:
lin_array = np.linspace(1, 10, 5)
print(lin_array)

[ 1.    3.25  5.5   7.75 10.  ]
